### name of file Must be 'Dockerfile'
### Every Docker file begins with "FROM " statement
FROM nginx:alpine

LABEL "Author"="Mahendra Shinde (MahendraShinde@synergetics-india.com"

COPY *.html /usr/share/nginx/html/